### PR TITLE
Remove dependency on ember-cli

### PR DESCRIPTION
**Pull request by trabus**
Removed dependency on ember-cli. Now using RSVP instead of `ember-cli/lib/ext/promise`, and passing in Blueprint to the `disable-npm-on-blueprint` helper instead of importing from ember-cli. Example usage:

```
var Blueprint        = require('ember-cli/lib/models/blueprint');
var BlueprintNpmTask = require('ember-cli-internal-test-helpers/lib/helpers/disable-npm-on-blueprint');
// usage
BlueprintNpmTask.disableNPM(Blueprint);
BlueprintNpmTask.restoreNPM(Blueprint);
```

### CODE REVIEW

**Comment by mmun** [comment]
I actually spiked this out myself so I'm glad you did it. I'm curious, was there a reason for doing this?

**Comment by trabus** [comment]
I want to bring the test helpers here into ember-cli, so removing the cyclical dependency is necessary.

**Comment by trabus** [comment]
@stefanpenner or @rwjblue do you have any problem with this causing a breaking change? I was going to bump the version of this in ember-cli-blueprint-test-helpers in conjunction with this change.

I'd like to bring this into ember-cli itself and remove the test helpers it replaces as well.

**Comment by rwjblue** [comment]
@trabus - Seems totally fine, as long as we bump the version appropriately (0.8.0 I think?)...

**Comment by stefanpenner** [comment]
LGTM, this reminds me to finish rsvp 4 and rsvp-party....

**Comment by trabus** [comment]
> @trabus - Seems totally fine, as long as we bump the version appropriately (0.8.0 I think?)...

Yeah, I was going to bump this to 0.8.0 as soon as I merge this PR tonight.

**Pull request merged**
