### PR TITLE
Fix usage of RSVP.Promise in run-command helper

### PR DESCRIPTION
**Pull request by ro0gr**

### CODE REVIEW

**Comment by ro0gr** [comment]
Strange appveyor failure https://ci.appveyor.com/project/embercli/ember-cli-internal-test-helpers/build/12/job/yctqdx7q73wbsy7f#L166 . Can't figure out what's happening here.

Looks like it's better to use some fake command in test instead of `mocha` like I [do it now](https://github.com/ember-cli/ember-cli-internal-test-helpers/pull/14/commits/edb2c0778d6e53237975031a4bbf15c0cc7ca05a#diff-128e967bfd935a7de2d13b62a96026c5R12). 
It should allow us have more deep test and avoid(I believe) such kind of appveyor issues.

Will try to re-write it today or tomorrow.

**Comment by trabus** [comment]
LGTM will merge once the tests are fixed.

**Comment by ro0gr** [comment]
Tests are fixed

**Comment by trabus** [comment]
@ro0gr Thanks for the PR!

**Pull request merged**
